name: Build and Deploy

on:
  push:
    branches:
      - main  # 触发条件：当代码推送到主分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true  # 如果使用的是 Hugo 扩展版本

    - name: Build
      run: pwd & ls -a

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
